#!/bin/bash
# Simple bash program to download music from youtube.
DEST_PATH=""
if ! which youtube-dl >/dev/null;
then
    echo "You must install youtube-dl utility to run this script."
    echo "for more information visit: https://rg3.github.io/youtube-dl/download.html"
    exit 2
fi

if [ -z $2 ];
then
    DEST_PATH="./"
else
	DEST_PATH="$2"
fi

if ! [ -d $DEST_PATH ] || ! [ -w $DEST_PATH ];
 then
	 echo "The destination directory doesn't exist or you don't have permission on It."
	 exit 2
 fi

if ! [ -z $1 ];
then
	echo "Destination: $DEST_PATH"
   	youtube-dl --ignore-errors --ignore-config --newline --output "$DEST_PATH/%(title)s.%(ext)s" \
     	--extract-audio --audio-quality 0 \
       	--embed-thumbnail --add-metadata --audio-format mp3 $1;
else
    echo "Use this script as follows: dmusic ( VIDEO_URL | PLAYLIST_URL ) [ DEST ]"
    exit 2
fi
exit 0
